config/routes.rb
Rails.application.routes.draw do
  get ".well-known/acme-challenge/:id" => "static_pages#letsencrypt"
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'comments/create'

  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get 'users/:id' => 'users#show', :as => 'user'
  get 'users/:id/edit' => 'users#edit', :as => 'edit_user'
  get 'users' => 'users#index', :as => 'users'
  delete 'users/:id',  to: 'users#destroy'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  

  resources :issues

  resources :comments, only:[:create]

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    #@issues  = [ { title: "Ruby lovers", comments: "4" }, 
      #{ title: "Rails and Laravel", comments: "5" } ]
      @issues = Issue.all
      # @users = User.all
    end

    def help
    end

    def about
    end

    def contact
    end

    def letsencrypt
     render text: "faN8XepsttirFwB1Dh4Jhp8vPUIbIpH0QVZbNLoDYLE.jSnYGXTvSCXx7AwLpjYYeGtIDS5dcEl_2wjnFsJe6hs"
   end
 end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_issue_list.html.erb
<div class="issue-list">
  <% issues.each do |i| %>
  <article class="issue clearfix">
    <div class="avatar">
      <%= link_to '#' do %>
      <%= image_tag i.user.avatar %>
      <% end %>
    </div>
    <div class="body">
      <h5 class="title">
        <%= link_to i.title, issue_path(i) %>
      </h5>
      <!-- <a class="read-more" href="#">read</a> -->
      <span class="meta-data">
        <%= link_to i.user.name, i.user %>
        <%= time_ago_in_words(i.created_at) %> <%= t("home.ago")%>
      </span>
    </div>
    <div class="issue-comment-count">
      <i class="fa fa-comments icon-muted"></i>
      <%= link_to i.comments.count, i %>
    </div>
  </article>
  <% end %>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
About Ruby on Rails Tutorial about the sample app at the
<a href="http://railstutorial.org/about">about page</a>.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
Contact Ruby on Rails Tutorial about the sample app at the
<a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
本网站头像服务来自Gravatar－全球公认的头像。
Gravatar是一图像跟随著您到访过的网站，当您在博客中留言或发表文章，它将会出现在您的名称旁。头像协助识别您在博客和论坛发表的文章，何乐而不为呢？
</p>

app/views/static_pages/home.html.erb
<header class="navbar navbar-fixed-top navbar-inverse clearfix navbar-transparent">
  <div class="splash" style="background-position: 0px 0px;">
    <div class="container">
      <nav>
        <a class="navbar-brand" href="/">
          <%= link_to "51yue", root_path, id: "logo" %>
        </a>

        <ul class="nav navbar-nav navbar-left">

          <li><%= link_to t("navbar.about"), about_path %></li>

          <li><%= link_to t("navbar.help"), help_path %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "登録したユーザー", users_path %></li>
          <% if logged_in? %>
          
          <li><%= link_to current_user.name, current_user %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to t("navbar.login"), login_path %></li>
          <li><%= link_to t("navbar.signup"), signup_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>


<% flash.each do |key, value| %>
<div class="alert-<%= key %>"><%= value %></div>
<% end %>





<div class="home-banner" data-stretch="<%= image_url "home-banner-bg.jpg" %>">
  <div class="center hero-unit">
    <h1><%= t("home.slogan") %></h1>

    <% if logged_in? %>

    <% else %>
    <%= link_to t("home.signup"), signup_path, class: "btn btn-large btn-primary" %>
    <% end %>
  </div>


  <div class="banner-inner container clearfix">
  </div>


</div>
<div class="issue-list-header">
  <div class="container clearfix">
    <div class="issue-list-heading"><%= t("home.issues") %></div>
    <div class="home-banner-links">
      <%= link_to t("home.contribute"), "/issues/new", class: "banner-btn btn" %>
    </div>
  </div>
</div>

<div class="container clearfix">  
  <%= render partial: 'issue_list', locals: { issues: @issues } %>
</div>

<script>
  $('.home-banner').anystretch();
</script>
<!--
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
-->