config/routes.rb
Rails.application.routes.draw do
  get ".well-known/acme-challenge/:id" => "static_pages#letsencrypt"
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'comments/create'

  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get 'users/:id' => 'users#show', :as => 'user'
  get 'users/:id/edit' => 'users#edit', :as => 'edit_user'
  get 'users' => 'users#index', :as => 'users'
  delete 'users/:id',  to: 'users#destroy'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  

  resources :issues

  resources :comments, only:[:create]

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 250 }
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  def new
    if not current_user
      flash[:success] = "log in first！"
      redirect_to login_path
    else
      @issue = Issue.new
    end
  end

  def show
    @issue = Issue.find(params[:id])
    @comments = @issue.comments
  end

  def create
    Issue.create(issue_params)
    redirect_to root_path
  end

  def destroy
    i = Issue.find(params[:id])
    i.destroy
    redirect_to root_path
  end

  def edit
    @issue = Issue.find(params[:id])
  end

  def update
    i = Issue.find(params[:id])
    i.update_attributes(issue_params)
    redirect_to root_path
  end

  private
  def issue_params
    params.require(:issue).permit(:title, :content, :user_id)
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_issue.html.erb
<li id="issue-<%= issue.id %>">
  <%= link_to gravatar_for(issue.user, size: 50), issue.user %>
  <!-- <span class="user"><%= link_to issue.user.name, issue.user %></span> -->
  <span class="content"><%= link_to issue.title, issue_path(issue.id) %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(issue.created_at) %> ago.
  </span>
</li>

app/views/issues/edit.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for @issue do |f| %>
    <dl class="form">
      <dt><%= f.label t("form.Title")%></dt>
      <dd><%= f.text_field :title %></dd>
    </dl>
    <dl class="form">
      <dt><%= f.label t("form.Content")%></dt>
      <dd><%= f.text_area :content %></dd>
    </dl>
    <p><%= f.submit t("release"), class: "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/issues/new.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for(Issue.new(user_id: current_user.id)) do |f| %>
    <%= f.hidden_field :user_id %>
    <dl class="form">
      <dt><%= f.label t("form.Title")%></dt>
      <dd><%= f.text_field :title %></dd>
    </dl>
    <dl class="form">
      <dt><%= f.label t("form.Content")%></dt>
      <dd><%= f.text_area :content %></dd>
    </dl>
    <p><%= f.submit t("release"), class: "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/issues/show.html.erb
<div class="issue-heading">
  <div class="container">
    <%= @issue.title %>
    <% if (current_user && current_user == @issue.user) || (logged_in? && current_user.admin) == true%>
    <%= link_to 'Destroy', issue_path(@issue), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
    <%= link_to 'edit', edit_issue_path(@issue), class: "btn btn-primary"%>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="replies">
    <article class="reply clearfix">
      <div class="avatar">
       <%= link_to @issue.user do %>
       <%= image_tag @issue.user.avatar, class: "image-circle" %>
       <% end %>
     </div>
     <div class="body">
      <div class="heading">
        <h5 class="name"><%= link_to @issue.user.name, @issue.user %></h5>
      </div>
      <!--<%= @issue.content %>-->
      <%= markdown @issue.content %>
    </div>
  </article>
  <% @comments.each do |c| %>
  <%= render partial: 'shared/comment', locals: {c: c} %>
  <% end %>
</div>
<% if current_user %>
<%= render partial: 'shared/comment_box', locals: {issue: @issue} %>
<% else %>
<%= link_to "先登录，后评论", login_path %>
<% end -%>
</div>