config/routes.rb
Rails.application.routes.draw do
  get ".well-known/acme-challenge/:id" => "static_pages#letsencrypt"
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'comments/create'

  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get 'users/:id' => 'users#show', :as => 'user'
  get 'users/:id/edit' => 'users#edit', :as => 'edit_user'
  get 'users' => 'users#index', :as => 'users'
  delete 'users/:id',  to: 'users#destroy'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  

  resources :issues

  resources :comments, only:[:create]

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse clearfix">
  <div class="container">
    <nav>
      <a class="navbar-brand" href="/">
        <%= link_to "51yue", root_path, id: "logo" %>
      </a>

      <ul class="nav navbar-nav navbar-left">

        <li><%= link_to t("navbar.about"), about_path %></li>

        <li><%= link_to t("navbar.help"), help_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "登録したユーザー", users_path %></li>
        <% if logged_in? %>
        <li><%= link_to current_user.name, current_user %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to t("navbar.login"), login_path %></li>
        <li><%= link_to t("navbar.signup"), signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body id="<%= params[:controller] + '-' + params[:action] %>">

  <% if params[:action] != 'home' %>
  <%= render 'layouts/header' %>
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <% end %>



  <%= yield %>

  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>

</body>
</html>